# Generated by Django 5.0.6 on 2024-05-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_domainknowledge_alter_resume_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='resume',
            name='domainKnowledge',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='keywords',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='techKnowledge',
            field=models.CharField(max_length=4000),
        ),
    ]
